<?php
use Icinga\Module\Monitoring\Object\Host;
use Icinga\Module\Monitoring\Object\Service;

if (! $this->compact): ?>
<div class="controls">
  <?= $this->tabs; ?>
  <?= $this->sortBox; ?>
  <?= $this->limiter; ?>
  <?= $this->paginator; ?>
  <?= $this->filterEditor; ?>
</div>
<?php endif ?>
<div class="content">
<?php

if (count($notifications) === 0) {
    echo $this->translate('No notifications found matching the filter') . '</div>';
    return;
}

$notificationReasons = array(
    1 => $this->translate('Problem acknowledgement'),
    $this->translate('Flapping started'),
    $this->translate('Flapping stopped'),
    $this->translate('Flapping was disabled'),
    $this->translate('Downtime started'),
    $this->translate('Downtime ended'),
    $this->translate('Downtime was cancelled'),
    99 => $this->translate('Custom notification')
);
?>
    <table data-base-target="_next" class="action">
    <tbody>
    <?php foreach ($notifications as $notification):
        if (isset($notification->service_description)) {
            $isService = true;
            $stateName = Service::getStateText($notification->notification_state);
            $stateDisplayName = Service::getStateText($notification->notification_state, true);
        } else {
            $isService = false;
            $stateName = Host::getStateText($notification->notification_state);
            $stateDisplayName = Host::getStateText($notification->notification_state, true);
        }

        $reason = (int) $notification->notification_reason;
    ?>
        <tr class="state <?= $stateName ?>">
            <td class="state">
                <strong><?= $stateDisplayName ?></strong><br />
                <?= $this->dateTimeRenderer($notification->notification_start_time)->render(
                    $this->translate('on %s', 'datetime'),
                    $this->translate('at %s', 'time'),
                    $this->translate('%s ago', 'timespan')
                ) ?>
            </td>
            <td class="notification-reason"><?= $reason === 0 ? (
                $notification->notification_state === 0
                    ? $this->translate('Recovery')
                    : $this->translate('Problem')
            ) : $notificationReasons[$reason] ?></td>
            <td style="font-size: 0.8em">
                <?php if ($isService): ?>
                    <?= $this->icon('service', $this->translate('Service')); ?>
                    <?= $this->link()->service(
                        $notification->service_description,
                        $notification->service_display_name,
                        $notification->host_name,
                        $notification->host_display_name
                    ) ?>
                <?php else: ?>
                    <?= $this->icon('host', $this->translate('Host')); ?>
                    <?= $this->link()->host($notification->host_name, $notification->host_display_name) ?>
                <?php endif ?>
                <br>
                <?= $this->escape($this->ellipsis($notification->notification_output, 10000)) ?>
                <br>
                <?php if (! $this->contact): ?>
                    <small>
                        <?= sprintf(
                            $this->translate('Sent to %s'),
                            $this->qlink(
                                $notification->notification_contact_name,
                                'monitoring/show/contact',
                                array('contact_name' => $notification->notification_contact_name)
                            )
                        ) ?>
                    </small>
                <?php endif ?>
            </td>
        </tr>
    <?php endforeach ?>
    </tbody>
    </table>
</div>
