<?php if (! $this->compact): ?>
<div class="controls">
  <?= $this->tabs; ?>
  <?= $this->sortBox; ?>
  <?= $this->limiter; ?>
  <?= $this->paginator; ?>
  <?= $this->filterEditor; ?>
</div>
<?php endif ?>
<div class="content">
<?php
$labels = array(
    'enabled'   => $this->translate('Enabled modules'),
    'disabled'  => $this->translate('Disabled modules'),
    'fail_load' => $this->translate('Enabled modules which have failed to load')
);
foreach ($modulesByState as $state => $modules) { ?>
  <h1><?= $labels[$state] ?></h1>
  <table class="action" data-base-target="_next">
    <tbody>
    <?php foreach ($modules as $module): ?>
      <tr>
        <td>
          <?= $this->qlink(
            $module->name,
            'config/module/',
            array('name' => $module->name),
            array('title' => sprintf($this->translate('Show the overview of the %s module'), $module->name))
          ); ?>
        </td>
      </tr>
    <?php endforeach ?>
    </tbody>
  </table>
<?php } ?>
</div>
